version: '3.9'
services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    # restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres